-- MySQL Workbench Synchronization
-- Generated: 2017-10-25 15:05
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Rafael Gomides

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE DATABASE `klshape`  DEFAULT CHARACTER SET utf8  DEFAULT COLLATE utf8_general_ci ;

CREATE TABLE IF NOT EXISTS `klshape`.`ALUNOS` (
  `ID_ALUNOS` INT(11) NOT NULL AUTO_INCREMENT COMMENT '								',
  `ALU_NOME` VARCHAR(100) NOT NULL,
  `ALU_RG` INT(9) NOT NULL,
  `ALU_CPF` INT(11) NOT NULL,
  `ALU_ENDERECO` VARCHAR(255) NOT NULL,
  `ALU_ATIVO` TINYINT(1) NOT NULL,
  `ALU_EMAIL` VARCHAR(50) NOT NULL,
  `ALU_SENHA` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_ALUNOS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `klshape`.`INSTRUTORES` (
  `ID_INSTRUTOR` INT(11) NOT NULL AUTO_INCREMENT,
  `INS_NOME` VARCHAR(100) NOT NULL,
  `INS_RG` INT(9) NOT NULL,
  `INS_CPF` INT(11) NOT NULL,
  `INS_ENDERECO` VARCHAR(255) NOT NULL,
  `INS_ATIVO` TINYINT(1) NOT NULL,
  `INS_EMAIL` VARCHAR(50) NOT NULL,
  `INS_SENHA` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_INSTRUTOR`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `klshape`.`NOTIFICACOES` (
  `ID_NOTIFICACAO` INT(11) NOT NULL AUTO_INCREMENT,
  `NOT_NOME` VARCHAR(45) NOT NULL,
  `NOT_DESCRICAO` VARCHAR(255) NOT NULL,
  `NOT_TIPO` VARCHAR(45) NOT NULL,
  `ALUNOS_ID_ALUNOS` INT(11) NOT NULL,
  `INSTRUTORES_ID_INSTRUTOR` INT(11) NOT NULL,
  PRIMARY KEY (`ID_NOTIFICACAO`, `ALUNOS_ID_ALUNOS`, `INSTRUTORES_ID_INSTRUTOR`),
  INDEX `fk_TREINAMENTOS_ALUNOS_idx` (`ALUNOS_ID_ALUNOS` ASC),
  INDEX `fk_TREINAMENTOS_INSTRUTORES1_idx` (`INSTRUTORES_ID_INSTRUTOR` ASC),
  CONSTRAINT `fk_TREINAMENTOS_ALUNOS`
    FOREIGN KEY (`ALUNOS_ID_ALUNOS`)
    REFERENCES `klshape`.`ALUNOS` (`ID_ALUNOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TREINAMENTOS_INSTRUTORES1`
    FOREIGN KEY (`INSTRUTORES_ID_INSTRUTOR`)
    REFERENCES `klshape`.`INSTRUTORES` (`ID_INSTRUTOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `klshape`.`EXERCICIOS` (
  `ID_EXERCICIO` INT(11) NOT NULL COMMENT '		',
  `EXE_NOME` VARCHAR(45) NOT NULL,
  `EXE_DATA` DATE NOT NULL,
  PRIMARY KEY (`ID_EXERCICIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `klshape`.`TREINAMENTOS` (
  `NOTIFICACOES_ID_NOTIFICACAO` INT(11) NOT NULL,
  `NOTIFICACOES_ALUNOS_ID_ALUNOS` INT(11) NOT NULL,
  `NOTIFICACOES_INSTRUTORES_ID_INSTRUTOR` INT(11) NOT NULL,
  `EXERCICIOS_ID_EXERCICIO` INT(11) NOT NULL,
  PRIMARY KEY (`NOTIFICACOES_ID_NOTIFICACAO`, `NOTIFICACOES_ALUNOS_ID_ALUNOS`, `NOTIFICACOES_INSTRUTORES_ID_INSTRUTOR`, `EXERCICIOS_ID_EXERCICIO`),
  INDEX `fk_NOTIFICACOES_has_EXERCICIOS_EXERCICIOS1_idx` (`EXERCICIOS_ID_EXERCICIO` ASC),
  INDEX `fk_NOTIFICACOES_has_EXERCICIOS_NOTIFICACOES1_idx` (`NOTIFICACOES_ID_NOTIFICACAO` ASC, `NOTIFICACOES_ALUNOS_ID_ALUNOS` ASC, `NOTIFICACOES_INSTRUTORES_ID_INSTRUTOR` ASC),
  CONSTRAINT `fk_NOTIFICACOES_has_EXERCICIOS_NOTIFICACOES1`
    FOREIGN KEY (`NOTIFICACOES_ID_NOTIFICACAO` , `NOTIFICACOES_ALUNOS_ID_ALUNOS` , `NOTIFICACOES_INSTRUTORES_ID_INSTRUTOR`)
    REFERENCES `klshape`.`NOTIFICACOES` (`ID_NOTIFICACAO` , `ALUNOS_ID_ALUNOS` , `INSTRUTORES_ID_INSTRUTOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NOTIFICACOES_has_EXERCICIOS_EXERCICIOS1`
    FOREIGN KEY (`EXERCICIOS_ID_EXERCICIO`)
    REFERENCES `klshape`.`EXERCICIOS` (`ID_EXERCICIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
